---
name: Devel-ebug-Wx
version: 0.05
author:
  - 'Mattia Barbon, C<< <mbarbon@cpan.org> >>'
abstract: GUI interface for your (d)ebugging needs
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0.27
  Class::Publisher: 0.2
  Config::IniFiles: 2
  Devel::ebug: 0.47
  File::UserConfig: 0.04
  Module::Pluggable: 3.1
  Wx: 0.61
  Wx::AUI: 0
  Wx::STC: 0
  YAML: 0.6
build_requires:
  Test::UseAllModules: 0
provides:
  DB:
    file: lib/Devel/ebug/Backend/Plugin/EvalLevel.pm
  Devel::ebug::Backend::Plugin::EvalLevel:
    file: lib/Devel/ebug/Backend/Plugin/EvalLevel.pm
  Devel::ebug::Backend::Plugin::State:
    file: lib/Devel/ebug/Backend/Plugin/State.pm
  Devel::ebug::Plugin::EvalLevel:
    file: lib/Devel/ebug/Plugin/EvalLevel.pm
  Devel::ebug::Plugin::FoldedStackTrace:
    file: lib/Devel/ebug/Plugin/FoldedStackTrace.pm
  Devel::ebug::Plugin::State:
    file: lib/Devel/ebug/Plugin/State.pm
  Devel::ebug::Plugin::Wx::StackTraceFrame:
    file: lib/Devel/ebug/Plugin/FoldedStackTrace.pm
  Devel::ebug::Wx:
    file: lib/Devel/ebug/Wx.pm
    version: 0.05
  Devel::ebug::Wx::Breakpoints::Pane:
    file: lib/Devel/ebug/Wx/View/Breakpoints.pm
  Devel::ebug::Wx::Command::NotebookEdit:
    file: lib/Devel/ebug/Wx/Command/NotebookEdit.pm
  Devel::ebug::Wx::Command::Run:
    file: lib/Devel/ebug/Wx/Command/Run.pm
  Devel::ebug::Wx::Command::ShowFile:
    file: lib/Devel/ebug/Wx/Command/ShowFile.pm
  Devel::ebug::Wx::Command::Standard:
    file: lib/Devel/ebug/Wx/Command/Standard.pm
  Devel::ebug::Wx::Command::Views:
    file: lib/Devel/ebug/Wx/Command/Views.pm
  Devel::ebug::Wx::Publisher:
    file: lib/Devel/ebug/Wx/Publisher.pm
  Devel::ebug::Wx::Service::Base:
    file: lib/Devel/ebug/Wx/Service/Base.pm
  Devel::ebug::Wx::Service::CodeDisplay:
    file: lib/Devel/ebug/Wx/Service/CodeDisplay.pm
  Devel::ebug::Wx::Service::CommandManager:
    file: lib/Devel/ebug/Wx/Service/CommandManager.pm
  Devel::ebug::Wx::Service::Configuration:
    file: lib/Devel/ebug/Wx/Service/Configuration.pm
  Devel::ebug::Wx::Service::Configuration::My:
    file: lib/Devel/ebug/Wx/Service/Configuration.pm
  Devel::ebug::Wx::Service::ViewManager:
    file: lib/Devel/ebug/Wx/Service/ViewManager.pm
  Devel::ebug::Wx::ServiceManager:
    file: lib/Devel/ebug/Wx/ServiceManager.pm
  Devel::ebug::Wx::View::Base:
    file: lib/Devel/ebug/Wx/View/Base.pm
  Devel::ebug::Wx::View::Breakpoints:
    file: lib/Devel/ebug/Wx/View/Breakpoints.pm
  Devel::ebug::Wx::View::Code::STC:
    file: lib/Devel/ebug/Wx/View/Code/STC.pm
  Devel::ebug::Wx::View::Eval:
    file: lib/Devel/ebug/Wx/View/Eval.pm
  Devel::ebug::Wx::View::Expressions:
    file: lib/Devel/ebug/Wx/View/Expressions.pm
  Devel::ebug::Wx::View::Multi:
    file: lib/Devel/ebug/Wx/View/Multi.pm
  Devel::ebug::Wx::View::Notebook:
    file: lib/Devel/ebug/Wx/View/Notebook.pm
  Devel::ebug::Wx::View::Output:
    file: lib/Devel/ebug/Wx/View/Output.pm
  Devel::ebug::Wx::View::StackTrace:
    file: lib/Devel/ebug/Wx/View/StackTrace.pm
no_index:
  package:
    - Devel::ebug::Backend::Plugin::ActionPoints
    - DB
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
